### ISSUE TITLE
 [Request for Python Lib] PyCryptodome

### ISSUE THREAD

**Issue by Maystern** [Leosang-lx/SUSTech-CS305-2023Fall#11]
In the ***Encryption*** section of the ***Bonus Part***, we need to implement *asymmetric* encryption and *symmetric* encryption. we want to use **RSA** encryption for asymmetric encryption and **AES** encryption for symmetric encryption. 

***Therefore, we would like to use the `PyCryptodome` library to facilitate the use of some cryptographic tools.***

> PyCryptodome is a comprehensive Python cryptography library that serves as a successor to PyCrypto (also known as Cryptodome or Crypto). Designed to offer modern and user-friendly cryptographic tools, this library supports a wide range of functionalities, including symmetric and asymmetric encryption, hash functions, message authentication codes (MAC), digital signatures, and cryptographic random number generation.

> Maintained by an international open-source community, PyCryptodome is widely used in applications requiring cryptographic support, such as secure communications, network security, and various other security-focused domains. It implements numerous standard cryptographic algorithms, including AES, RSA, DES, Triple DES, SHA-1, SHA-256, SHA-512, among others.

> For developers working on cryptographic tasks in Python, PyCryptodome is a powerful and trusted choice. It provides a platform for implementing encryption, decryption, digital signatures, hash functions, and other cryptographic operations. 

***In our approach, we will use `PyCryptodome` to implement AES and RSA encryption.***

Therefore, we suggest adding the `PyCryptodome` library to the whitelist library of this project.

Thanks for reading, we are looking forward to your kind reply.

**Comment by Mark4551124015** [comment]
[Accepted] Free to go. As long as it's not related to HTTP directly.
