### ISSUE TITLE
About URL percent encoding.

### ISSUE THREAD

**Issue by Gralerfics** [Leosang-lx/SUSTech-CS305-2023Fall#12]
If I have a file named `!akj  skdjTkj#$# abc.jpg`, the url of GET request will be `http://localhost/client1/!akj%20%20skdjTkj#$#%20abc.jpg`. Unfortunately `#` in url means anchor which will be ignored by the browser in the request line, i.e. the request url will become `http://localhost/client1/!akj%20%20skdjTkj` without the characters after the first `#`.
Perhaps this problem can only be solved by modifying the API?

Similar problem for `&` and `=` in the get parameters in GET request. e.g. `/delete?path=/client1/test - 中文/25 - 副本^&!@=2&a.png`, we cannot correctly parse urls like this, unless modifying API. Or we can assume that there won't be more than one parameter after `?`, but it is against the rules of url and may not a good idea.

In additional: Should we consider the case that Chinese characters occur? Should we use ".encode('ISO-8859-1').decode('utf-8')"?

**Comment by Mark4551124015** [comment]
We don't exam your coding robustness like this. All tested file name will be guarantee in leagle file name (i.e. base64 encoded, number and english characters)

**Comment by Gralerfics** [comment]
Thank you.
