### ISSUE TITLE
About automatically directories creating in `upload`.

### ISSUE THREAD

**Issue by Gralerfics** [Leosang-lx/SUSTech-CS305-2023Fall#13]
> 8. Doesn't matter. Since this directory will be create automatically when using `HTTP Post` is upload it's file.

In https://github.com/Leosang-lx/SUSTech-CS305-2023Fall/issues/10#issuecomment-1826484005

请问，`upload`需要自动建立不存在的目录，但如果某目录下有一非目录文件和想建的某级目录同名，同目录下又没法有同名的文件和目录，这时候是要报个403还是什么的错吗？

Thank you.

**Comment by Leosang-lx** [comment]
前面8.这个回答的upload自动创建目录应该只是对于用户根目录的
对于上传的目标路径不存在的情况文档里有说：If the target directory to upload file to does not exist in the server, the server should return `404 Not Found`

**Comment by Gralerfics** [comment]
Thank you.
