### ISSUE TITLE
Discrepancy between docs and test script

### ISSUE THREAD

**Issue by Charley-xiao** [Leosang-lx/SUSTech-CS305-2023Fall#14]
In terms of the parameter `path` in uploading files, the document shows, for one, `path=/11912113` as well as `path=/11912113/`. In the test script given, nonetheless, it uses `path=11912113/`.

Since we are writing the parser on our own, it is important for us if you could specify which of the following format should be the correct one if a file is to be uploaded to the root directory of the user `11912113`:

`path=/11912113`

`path=11912113/`

`path=/11912113/`

Thanks!

**Comment by Mark4551124015** [comment]
This is an robust issue since you can handle 3 cconditions easily, by post progressing of the path string. Btw, you should handle the condition `path=11912113` too. (Since the `path` is alway a folder name)

**Comment by Charley-xiao** [comment]
> This is an robust issue since you can handle 3 cconditions easily, by post progressing of the path string. Btw, you should handle the condition `path=11912113` too. (Since the `path` is alway a folder name)

Got it. Thanks!
