### ISSUE TITLE
About breakpoint transmission.

### ISSUE THREAD

**Issue by Gralerfics** [Leosang-lx/SUSTech-CS305-2023Fall#15]
What is the meaning of "And we will test whether the transmission can be resumed after a short pause" in the document?

This part told us to implement the header `Range`, is the requirement means that we should implement a client which support breakpoint transmission based on `Range`? And what is `a short pause` exactly referred to? 

If a client is to be implemented, does this mean that the client is shut down halfway through the transfer, and the next time the user logs in as that user, the client is allowed to request the server to send the file at the last breakpoint? Is this part of the logic to be implemented by the client or the server?

Thank you.

**Comment by Leosang-lx** [comment]
The pause and continuation of downloading here are achieved by the client requesting file contents of different ranges.
You don't need to implement a client and submit, the corresponding test script is a simple client to test the functionality. However, you can use a **browser** to download from server or implement a simple client to download with different ranges of file content to test your breakpoint transmission, and you are recommanded to test or show its functionality in your own way in **presentation**.

**Comment by Gralerfics** [comment]
Got it. Thank you!
