### ISSUE TITLE
Questions about view and download part

### ISSUE THREAD

**Issue by lnsxy** [Leosang-lx/SUSTech-CS305-2023Fall#20]
1. The './' and '../' appears in the Project Document, but test demo doesn't have them.
2. The Project Document says "If the requested path is a folder, the query parameter SUSTech-HTTP=[01] is required", but the html generated by test demo ignored them. For example,\<li>\<a href="client1/">client1/\</a>\</li>.
Can you give further information?

**Comment by Leosang-lx** [comment]
1. This two link just make a more convenient front end for user to interact, but can be unnecessarily included when `SUSTech-HTTP=1`.
2. I have no idea about your second question. Just to explain again: when the target path of request corresponds to a fold, then it has two kinds of response controlled by parameter `SUSTech-HTTP`; when the target path of request corresponds to a file, then it has the only one kind of response, that's the file content, which won't be affected by the value of `SUSTech-HTTP`.

**Comment by Mark4551124015** [comment]
It's a valid request lead to 404 NOT FOUND if that path is not exists. SUSTech-HTTP=1 is just an args that indicate `NO FRONT END HTML REQUIRED`. You should always handle any kinds of url requests. :)

**Comment by Leosang-lx** [comment]
> 1. These two items just make a more convenient front end for user to interact, but can be unnecessarily included when `SUSTech-HTTP=1`.
> 2. I have no idea about your second question. Just to explain again: when the target path of request corresponds to a folder, then it has two kinds of responses controlled by parameter `SUSTech-HTTP`; when the target path of request corresponds to a file, then it has the only one kind of response, the file content, which won't be affected by the value of `SUSTech-HTTP`.

Correct: `SUSTech-HTTP` is only **required** when client wants the response include items of requested path in **list**, which aims **for the convenience of testing**. Otherwise server will response the corresponding **`html` page** if no `SUSTech-HTTP` parameter is provided or with query parameter `SUSTech-HTTP=1`.

**Comment by lnsxy** [comment]
I got it, but I think description is ambiguous in the project document. Perhaps it needs update?
Anyway, many thanks!

**Comment by Leosang-lx** [comment]
> I got it, but I think description is ambiguous in the project document. Perhaps it needs update? Anyway, many thanks!

Yes, I will update the document soon.

**Comment by lnsxy** [comment]
Thanks again.
