### ISSUE TITLE
ask about upload/view

### ISSUE THREAD

**Issue by oops413** [Leosang-lx/SUSTech-CS305-2023Fall#24]
1. 在没有用户根目录的时候上传文件 比如path = /username/会自动新建目录，那其他情况比如path=/username/bb/，bb目录不存在不会新建，这样用户根目录下不就一直不可能有目录？
2. /是根目录，也就是[peoject dir] 那他就永远不能点击吧？

**Comment by Leosang-lx** [comment]
1. 测试只是基于已有的文件目录进行，也就是说用户文件夹下面可能已经有一些文件及文件夹。并且，本次project重点还是在网络传输上，让大家了解http的底层原理，因此各项部分其实都简化了，并没有要求大家从用户端来新建文件夹。大家测试当然也是提前放一点文件和文件夹上去。当然把功能实现丰富了，也可以作为一定量的bonus在答辩展示出来。
2. /对应/data/目录，也就是用户目录的父目录，应该是可以点击的并跳转的。"/"和"../"是为了前端页面更方便使用添加上去的，实际情况还是参考测试样例吧。

**Comment by oops413** [comment]
不好意思我还是有点不明白第二个问题（还没有测试样例所以想再问一下） /可以点击跳转意味着可以看到/data下的所有目录，这对用户来说是有这个权限的吗

**Comment by Leosang-lx** [comment]
> 不好意思我还是有点不明白第二个问题（还没有测试样例所以想再问一下） /可以点击跳转意味着可以看到/data下的所有目录，这对用户来说是有这个权限的吗

0.0是有的。文档中只说了对于upload和delete操作，也就是涉及到修改服务器内容的操作会对受到用户权限限制，但是对于view和download，任何用户都是有权限的（前提是现存的用户）。
如果是因为文档中没强调这一方面导致理解有误，抱歉带来困扰了。下一次文档更新会再明确一下这方面的说明

**Comment by oops413** [comment]
谢谢！
