### ISSUE TITLE
[request for new lib] ssl

### ISSUE THREAD

**Issue by andychenggg** [Leosang-lx/SUSTech-CS305-2023Fall#25]
可以使用ssl库获取ssl证书并且构建https么？还是说要手动实现tls握手，加密解密，手动构建证书并向客户端提供证书？

**Comment by Leosang-lx** [comment]
[Unaccepted] 不好意思，ssl在本次project中是不允许使用的，可以使用其他比如cryptography的加密库来实现

**Comment by andychenggg** [comment]
@Leosang-lx 
![image](https://github.com/Leosang-lx/SUSTech-CS305-2023Fall/assets/100212381/32c3765d-4d50-4b47-92cd-1ec137fa4c9f)
根据task，我们的任务是完成这些内容，那如何检验https功能的实现呢？按道理来说，只完成task中的内容是无法使用浏览器访问的。

**Comment by Leosang-lx** [comment]
这部分只要求根据给定流程完成一个沟通密钥和加密传输的过程，不需要实现完整的https。需要在答辩时提供一个传输场景，展示并体现出你的加密传输的沟通密钥和加密传输的过程，并对你的方法进行简要的分析。
