### ISSUE TITLE
About header `Range`.

### ISSUE THREAD

**Issue by Gralerfics** [Leosang-lx/SUSTech-CS305-2023Fall#27]
1. In test demo there used
```
headers={..., "Range": "0-1,1-2,2-3"}
```
However in the document and standards, it should be `Range: <unit>=<ranges>`, i.e. `Range: bytes=0-1,1-2,2-3`. Which one should we adopt?

2. And if the request has `Range` like `0-100,50-200` (overlapping, which is asserted as legal but not canonical), whether we should return two ranges separately or combine them?

3. In addition, should there be a `Content-Range` in header when there is only one range?

4. Moreover, when the client requests for a directory (html page), is `Range` allowed to use?

**Comment by Mark4551124015** [comment]
Q1: The default setting is bytes. You should handle all cases actually.
Q2: Seperately
Q3: Yes
Q4: no, only file requests is included.

**Comment by Mark4551124015** [comment]
P.S. If you design all funcitons follow corresponding to RFC, you should get the full mark  :)

**Comment by Gralerfics** [comment]
Thank you.
