### ISSUE TITLE
encryption部分

### ISSUE THREAD

**Issue by ZhangYP21** [Leosang-lx/SUSTech-CS305-2023Fall#29]
1.encryption部分直接实现RSA算法可以吗？
2.交换公钥这个过程可以自己定义一个特定header或者msg内容或者指定路径来表示这是一个交换密钥的过程吗（以保证公钥正确交换）？不手搓TLS/SSL 握手过程。这部分是不是只要保证合理交换密钥，正确encode，decode就可以？具体实现方法合理就行？

**Comment by Leosang-lx** [comment]
1. 可以的
2. 对，能够体现出你的加密过程并且合理就行即可，不需要手搓tls/ssl

**Comment by ZhangYP21** [comment]
好的！感谢！！！
