### ISSUE TITLE
[Request for Python Lib] selectors, enum, re

### ISSUE THREAD

**Issue by Gralerfics** [Leosang-lx/SUSTech-CS305-2023Fall#3]
`selectors` for managing the socket threads (substitute for `threading`);
`enum` (and other basic python packages);
`re` for parsing routings.

**Comment by Mark4551124015** [comment]
selectors [Accepted]

**Comment by Mark4551124015** [comment]
`selectors` [Accepted]
`enum`      [Accepted] But only for this package, since we are using whitelist. (e.g. `http` is also a python basic package and that is unacceptable)
`re`            [Accepted]
