### ISSUE TITLE
[Request for Python Lib]pycryptodome，hashlib

### ISSUE THREAD

**Issue by ZhangYP21** [Leosang-lx/SUSTech-CS305-2023Fall#34]
1. pycryptodome used for encryption
2.hashlib用于将对称密钥散列为256位（32字节）的密钥，以满足AES加密算法的要求。

**Comment by Leosang-lx** [comment]
`pycryptodome` [Accepted], has been mentioned in the previous issue
`hashlib` [Accepted]
