### ISSUE TITLE
encryption

### ISSUE THREAD

**Issue by oops413** [Leosang-lx/SUSTech-CS305-2023Fall#35]
请问我一定要将密钥信息放在HTTP报文中传输嘛，可以在验证身份之后就用socket进行交换密钥吗

**Comment by Leosang-lx** [comment]
可以吧。。。？这部分不属于标准http范畴，因此需要自定义客户端对接相应的加密过程及功能来进行展示。只要你的客户端能够正常沟通加密及访问服务器即可。

**Comment by oops413** [comment]
那请问这一部分可以和basic部分分开测试吗

**Comment by Leosang-lx** [comment]
当然的，并且这一部分需要自己提供测试，并在答辩中展示

**Comment by oops413** [comment]
谢谢！
