### ISSUE TITLE
[Request for Python Lib] posixpath

### ISSUE THREAD

**Issue by ITBillZ** [Leosang-lx/SUSTech-CS305-2023Fall#36]
消除冗余的分隔符：normpath 会移除路径中多余的斜线（/）。例如，//my//path// 会被转换成 /my/path/。

解决相对路径：它还能处理路径中的 .（代表当前目录）和 ..（代表上级目录）。例如，/my/path/../another/ 会被转换成 /my/another/。

统一路径格式：用于使路径的格式统一，即使在不同的操作系统上。

**Comment by Leosang-lx** [comment]
[Accepted]
