### ISSUE TITLE
Question about chunk transfer

### ISSUE THREAD

**Issue by 2069958859** [Leosang-lx/SUSTech-CS305-2023Fall#37]
Does the implementation of block transfer just send the file back together in a format like body or transfer it one piece at a time?
(中文翻译：请问分块传输的实现是只是把文件分成文档中body那样的格式一起传回去还是一块一块分多次传输回去？)

**Comment by Mark4551124015** [comment]
这属于是对HTTP传输的理解，看看RFC里chunked transfer的目的，以及如何实现发送？

**Comment by 2069958859** [comment]
好的，谢谢
