### ISSUE TITLE
Ambiguity in listing files

### ISSUE THREAD

**Issue by Charley-xiao** [Leosang-lx/SUSTech-CS305-2023Fall#39]
With parameter `SUSTech-HTTP=1`, the document states that we should respond with **a list of files** under the requested directory.

In the test script, however, we see `['12589/', 'a.py', 'a.txt', 'client1/', 'client2/', 'client3/']` as an example of the returned list yet encountering `client1/`, `client2/` *et cetera* as **directories** instead of **files**. 

Furthermore, taking into consideration the possibility that files, as well as sub-directories, exist, if not directly, under the requested directory, I doubt whether it is required as well to list them as they're inherently **files** under the directory, literally.

It would be nice if you could resolve such ambiguity in both the document and the test script. Thanks!

**Comment by Leosang-lx** [comment]
Document has been updated, hopefully it won't make you confused any more. :)

**Comment by Charley-xiao** [comment]
> Document has been updated, hopefully it won't make you confused any more. :)

Got it. Thanks!
