### ISSUE TITLE
About encryption

### ISSUE THREAD

**Issue by XiaoLeGG** [Leosang-lx/SUSTech-CS305-2023Fall#41]
中文:
我已经在服务端实现了加密连接，但是这玩意是需要客户端主动开启的（什么废话

我的问题是：对于加密情况，我需不需要完整的演示所有功能在加密情况下的表现？我目前的前端是基于浏览器，默认不开启加密的。对于加密的测试和演示，我认为是不是只需要准备简单的一个或者两个用例（在ipynb上或者单独的代码）就足够了？

English:
I have implemented encryption function but it should be enable by client (of course.

My question is: For encryption scenarios, do I need to fully demonstrate all functionalities under encrypted conditions? My current front-end is browser-based and does not support encryption. For testing encryption, is it enough to jprepare just one or two simple use cases (on ipynb or separate code)?

**Comment by Leosang-lx** [comment]
是的，比如对于服务器的download和upload服务进行加密通信的测试即可。当然如果经过了较为充分的测试，也可以将不同测试结果列出来
（话说这种不属于标准http的是如何能够用浏览器支持的？还是你差不多手搓了一个https或者用的其他某些浏览器支持的加密协议？）

**Comment by XiaoLeGG** [comment]
> 是的，比如对于服务器的download和upload服务进行加密通信的测试即可。当然如果经过了较为充分的测试，也可以将不同测试结果列出来 （话说这种不属于标准http的是如何能够用浏览器支持的？还是你差不多手搓了一个https或者用的其他某些浏览器支持的加密协议？）

我并没有实现用浏览器支持，或者说，如实现。直接用浏览器访问网页而发送的请求肯定没办法做加密（至少我还没想到），最多可以在返回的html的前端js代码里对一些GET、POST请求做加密。比如upload，密码验证这些，但既然说不需要那我也就不做了（
