### ISSUE TITLE
About test demo

### ISSUE THREAD

**Issue by andychenggg** [Leosang-lx/SUSTech-CS305-2023Fall#45]
url='http://127.0.0.1:8080/'
headers={"Authorization": "Basic dXNlcjE6cGFzczE="}
r=requests.get(url=url, headers=headers)
print(r.cookies)
print(r.cookies.values()[0])
headers={"Cookie":'session-id='+r.cookies.values()[0]}
q=requests.get('http://localhost:8080/',headers=headers)
这里面两个请求时属于两个不同的连接吧？第二个连接拿着第一个连接的sessionid作为自己的cookie，怎么能够返回200呢？

**Comment by Leosang-lx** [comment]
这里的cookie的作用是简化的，只为了提供用户的登录信息，相当于在该用户对应的新的sessionid产生前，客户端都可以通过这个sessionid给服务器提供该user的认证信息
