### ISSUE TITLE
Questions about Support Many Clients

### ISSUE THREAD

**Issue by ZhangYP21** [Leosang-lx/SUSTech-CS305-2023Fall#48]
用不用考虑多个client对同一个文件进行IO操作的情况？比如多线程加锁之类的？
看文档好像主要说了处理并发，在某一个client出问题时不影响其他线程，并没有说明用不用处理读写冲突等问题

**Comment by Mark4551124015** [comment]
放心，这种鲁棒不在考虑之内，最多会同时读取，不会存在同时写入问题

**Comment by ZhangYP21** [comment]
> 放心，这种鲁棒不在考虑之内，最多会同时读取，不会存在同时写入问题

好的太感谢了！！！
