### ISSUE TITLE
Question about cookie expire time

### ISSUE THREAD

**Issue by Tangent-H** [Leosang-lx/SUSTech-CS305-2023Fall#49]
cookie的expire time是从什么时间开始计算的？
是在cookie生成的那一个时刻就要指定吗（比如说生成后的30s失效）？
还是在当前这个用户退出登录（conn.close()）之后开始算（cookie的expire time设置成用户退出登录后的30s内失效）？
文档中说的是“Also this session-id will become expired if the user doesn't login again
in a certain period of time,”看起来说的是从退出后开始计时，那是不是如果用户在cookie expire之前用了这个session id登录，下次退出又会刷新这个expire time

**Comment by Leosang-lx** [comment]
“become expired if the user doesn't login again in a certain period of time”这里应该还是说是从上一次login操作开始计时，也就是**第一次使用用户名密码成功登陆** 或者 **成功使用这个cookie进行登陆**开始算，而不是断开连接才开始算。@Mark4551124015 ，方便的话帮我看看有没有毛病（）

**Comment by Tangent-H** [comment]
明白了，我准备采用第一种方式，谢谢！
