### ISSUE TITLE
[Request for Python Lib] sqlite3, pickle

### ISSUE THREAD

**Issue by Gralerfics** [Leosang-lx/SUSTech-CS305-2023Fall#5]
`sqlite3` for persistently storing the accounts, cookies, etc. (`sqlite3.def/.dll` might need to be contained in the project folder)
or `pickle`.

By the way, how is the testing done roughly?
Is the `data` directory provided by the test side or is it carried in the code?
And is it allowed to include some static resources like html, js, etc. in the project directory?
Should the root virtual directory (e.g. `http://localhost:8080/`) also be exhibited and be open to all the users?

Thank you!

**Comment by Leosang-lx** [comment]
[Accepted] `sqlite3, pickle`
The directories and files inside `data` will be provided in formal testing, and you should also carry it in your code since `http://localhost:8080/` is mapped to `/data/`.
