### ISSUE TITLE
Question about path format in delete

### ISSUE THREAD

**Issue by SusTzzm2003** [Leosang-lx/SUSTech-CS305-2023Fall#52]
According to the announcement, path formats like "?path=client1" should be supported by server when deleting. Does it mean that, deleting a whole directory should be supported by server? Because as the project document said, the request url should be like this: http://localhost:8080/delete?path=/11912113/abc.py, which ends with a specific file.

就我的理解而言，delete的request url后面跟的应该是一个具体的文件如a.txt或a.py，那如果要兼容文件夹不加分隔符 ("?path=client1") 的情况，url就会长成这样: ("?path=client1a.py")，该如何区分文件夹和文件呢？还是说，有些情况下delete request的url中只有文件夹，没有具体的文件，如 http://localhost:8080/delete?path=11912113，我们需要在delete功能中支持删除整个文件夹的功能？

**Comment by Leosang-lx** [comment]
Yes, the query parameter is just the **path**, which can refer to any position, file or folder under the root directory. And the server should simply execute the deleting operation if the **target path exists** (no matter file or folder) and the user has the **permission** to delete
