### ISSUE TITLE
[Request for Python Lib] urllib

### ISSUE THREAD

**Issue by Charley-xiao** [Leosang-lx/SUSTech-CS305-2023Fall#6]
It would be nice if `urllib` is allowed since, specifically, `urlparse()` and `parse_qs()` in `urllib.parse` facilitates parsing requests for files with parameters.

**Comment by Mark4551124015** [comment]
[Unaccepted] Since `urllib.request` included functions related to HTTP services, we do not encourage such utilization. Write yourself a better parser! Enjoy it!
