### ISSUE TITLE
Question about encryption presentation

### ISSUE THREAD

**Issue by SusTzzm2003** [Leosang-lx/SUSTech-CS305-2023Fall#61]
When we are presenting about the encryption part, can we use only upload (with different types of files being uploaded simultaneously) to demonstrate that we've implemented encryption feature? Because we may need to walk through our code, and use Wireshark to capture packets, which will usually take some time.

**Comment by Leosang-lx** [comment]
You should show that a client can correctly access **some** of the services provided by server. Then you can choose upload as the example in your presentation, but a little bit more examples can be better.
Also, you can choose your own way to clearly explain how your encryption works, and remember to control the time of presentation.
