### ISSUE TITLE
Question about the test demo

### ISSUE THREAD

**Issue by stc-W** [Leosang-lx/SUSTech-CS305-2023Fall#63]
![q1](https://github.com/Leosang-lx/SUSTech-CS305-2023Fall/assets/107791364/92b5db55-68c7-4e54-8d54-726709ac543d)
![q2](https://github.com/Leosang-lx/SUSTech-CS305-2023Fall/assets/107791364/d64bb0d6-ab97-4763-8adb-f76506d204c4)
In the breakpoint section, do we need  to merge two segment into one segment if two segments overlap? I think in pdf the answer is yes, but in test demo the three segment 0-1, 1-2, 2-3 are seen as three parts. I just reply one segment 0-3 bytes.

**Comment by Leosang-lx** [comment]
Not necessary, just reply according to the request ranges, which is also mentioned previously

**Comment by stc-W** [comment]
thx
