### ISSUE TITLE
Speed up test baseline

### ISSUE THREAD

**Issue by Jackychenji** [Leosang-lx/SUSTech-CS305-2023Fall#64]
为了更好的实现，我们能知道最终测试时传输数据的大小以及baseline的时间吗（large file downloading with one client），以及用户的个数与传输时间（small file downloading with multiple clients）

**Comment by Leosang-lx** [comment]
这个还没定，因为还不知道大家实现的情况，所以得等大家都交了才能测出来。当然这个baseline是从低设置的，因此大部分人这部分应该都能拿到分。然后后面的测试我还没拿到脚本。。。 @Mark4551124015 如果你清楚的话帮我看一下吧（）
