### ISSUE TITLE
About Presentation

### ISSUE THREAD

**Issue by susjunyou** [Leosang-lx/SUSTech-CS305-2023Fall#65]
Do we need to run the code presentation at presentation time, if there has a front end. Or just need show the web by video or picture in my slides.

**Comment by susjunyou** [comment]
one more question, should we consider upload a file, but there has a  same name file in upload path folder.
.

**Comment by susjunyou** [comment]
If my teammate is not in the same lab class, what is the presentation date?

**Comment by Leosang-lx** [comment]
> Do we need to run the code presentation at presentation time, if there has a front end. Or just need show the web by video or picture in my slides.

At least a short video, run the server and show the front-end can be better


> one more question, should we consider upload a file, but there has a same name file in upload path folder. .

If there is a file with same name, you can simply cover this file with new file content



> If my teammate is not in the same lab class, what is the presentation date?

Choose appropriate presentation time
