### ISSUE TITLE
Question about Authentication and Cookies

### ISSUE THREAD

**Issue by KouHiiChan** [Leosang-lx/SUSTech-CS305-2023Fall#66]
1. Since we're implementing HTTP1.1, whose connection is persistent by default, should we check authentication field of EVERY request? Or just the first to build a connection(Client can just authenticate at the first time, and send other requests without authentication field later in the same connection) ?

If the answer is YES:
    What if the client requests with another client's correct Authentication info after some requests? Should we respond 401, 403 or switch the identity?

2. Can Cookie replace the Athentication field?

**Comment by KouHiiChan** [comment]
By the way, when uploading, if path=NULL, should we respond 400, 401 or 404?

**Comment by KouHiiChan** [comment]
Additionally, when uploading, the client only provide the uploading directory, but what's the file name?

**Comment by Leosang-lx** [comment]
> Additionally, when uploading, the client only provide the uploading directory, but what's the file name?

#8 


> By the way, when uploading, if path=NULL, should we respond 400, 401 or 404?

400

> 1. Since we're implementing HTTP1.1, whose connection is persistent by default, should we check authentication field of EVERY request? Or just the first to build a connection(Client can just authenticate at the first time, and send other requests without authentication field later in the same connection) ?
> 
> If the answer is YES: What if the client requests with another client's correct Authentication info after some requests? Should we respond 401, 403 or switch the identity?
> 
> 2. Can Cookie replace the Athentication field?

Need to check authentication in the following field **OR** check the sessionID in cookie. And you can set higher priority for sessionID. (Since we temporarily implement in this way, but this make it difficult to switch user...)

**Comment by KouHiiChan** [comment]
Thanks.
