### ISSUE TITLE
About test demo: test POST method

### ISSUE THREAD

**Issue by KouHiiChan** [Leosang-lx/SUSTech-CS305-2023Fall#71]
<img width="979" alt="屏幕截图 2023-12-29 052451" src="https://github.com/Leosang-lx/SUSTech-CS305-2023Fall/assets/131244549/ff41c406-2c11-4892-9a04-f8922f2d7240">
I think this should return 400 but not 405.
According to RFC 9110 (link: https://httpwg.org/specs/rfc9110.html#status.401)， 

    Section 15.5.1:

        The 400 (Bad Request) status code indicates that the server cannot or will not process the request due to something that is 
        perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

    Section 15.5.6:

        The 405 (Method Not Allowed) status code indicates that the method received in the request-line is known by the origin server but 
        not supported by the target resource. The origin server MUST generate an Allow header field in a 405 response containing a list of 
        the target resource's currently supported methods.

405 means the request have a known method like GET, POST, HEAD, for instance, PUT, but PUT is not supported by the server, then the server respond with a 405 status code. It's not the syntax error of HTTP basic format, but the rule that server makes.

**Comment by Leosang-lx** [comment]
The target resouce here is now the html file or the binary content of  a certain file, which is only supported to be accessed by GET method here. Besides, the boundary cases shown in document have cover most situation, and our test will not focus on testing the boudary cases of the requests, but to test the robustness of your server, so don't worry too much about these cases.

**Comment by KouHiiChan** [comment]
Thanks
