### ISSUE TITLE
脚本测试方面

### ISSUE THREAD

**Issue by Jackychenji** [Leosang-lx/SUSTech-CS305-2023Fall#73]
脚本会测试png等非常规文件的上传吗，如果有的话能否告知具体测试的文件类型

**Comment by Jackychenji** [comment]
测试下载速度的时候是同一台机子测试还是不同机子测试

**Comment by Leosang-lx** [comment]
> 脚本会测试png等非常规文件的上传吗，如果有的话能否告知具体测试的文件类型

常见的都可能会测吧，我还没看到测试脚本，想问下你哪里处理有问题呢



> 测试下载速度的时候是同一台机子测试还是不同机子测试

要公平那自然得同一台机子测试吧

**Comment by Jackychenji** [comment]
> > 常见的都可能会测吧，我还没看到测试脚本，想问下你哪里处理有问题呢
> 
> 就是想问问会不会和本地的测试一样，会不会有别的格式的文件
> 
> > 要公平那自然得同一台机子测试吧
> 
> 这个想问一下就是server和client在一台机子上还是两台机子
