### ISSUE TITLE
关于测试脚本的一些问题

### ISSUE THREAD

**Issue by ITBillZ** [Leosang-lx/SUSTech-CS305-2023Fall#75]
测试脚本中多处允许请求data根目录，这似乎与文档内容相悖。
<img width="361" alt="image" src="https://github.com/Leosang-lx/SUSTech-CS305-2023Fall/assets/47292916/d1ca27bc-be6f-41cb-8f5c-c7c41e5116fe">

<img width="656" alt="image" src="https://github.com/Leosang-lx/SUSTech-CS305-2023Fall/assets/47292916/e40f2f97-cc6f-4081-883a-11d4ef68ad7b">

**Comment by Leosang-lx** [comment]
请仔细阅读文档，这个对应的目录是/data目录，是在位于你的项目根目录的一个文件夹: `[root directory to project]/data/`
