### ISSUE TITLE
what is the file name when uploading

### ISSUE THREAD

**Issue by HaoyuWang141** [Leosang-lx/SUSTech-CS305-2023Fall#8]
It seems like that query parameters only contain "path" but not anything abous "filename".

![image](https://github.com/Leosang-lx/SUSTech-CS305-2023Fall/assets/108910511/e9c80b98-d387-401b-b5c5-5df64ba6f48e)

**Comment by Mark4551124015** [comment]
Check the HTTP 1.1 POST method (You can try it with `requests` localy) Which will cover informations about uploading files. So the filename is unrequired in URL args
